# Generated by Django 4.1 on 2023-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ci', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField()),
                ('fecha', models.DateField()),
                ('justificacion', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('project_id', models.IntegerField()),
                ('horaFin', models.TimeField()),
                ('horaInicio', models.TimeField()),
                ('fechaSolicitud', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pending', max_length=10)),
                ('descripcion', models.TextField()),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Petition',
        ),
    ]
