# Generated by Django 4.1 on 2023-09-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabio', '0002_registroestudiantes_registropermisos_delete_petition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropermisos',
            name='project_id',
        ),
        migrations.AddField(
            model_name='registropermisos',
            name='id_solicitud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registropermisos',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fabio.registroestudiantes'),
        ),
        migrations.AlterField(
            model_name='registroestudiantes',
            name='ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroestudiantes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='fechaSolicitud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='horaFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='horaInicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registropermisos',
            name='materia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
